Feature: Tree

  Scenario: Verify Tree values
    Given I open extjs6 app and add "#tree-xml" path
    Then I verify if Tree has values:
      | v Ext JS                 |
      | -> app                   |
      | -> button                |
      | -> container             |
      | -> dashboard             |
      | -> dd                    |
      | -> dom                   |
      | -> flash                 |
      | -> form                  |
      | -> fx                    |
      | -> grid                  |
      | -> layout                |
      | -> menu                  |
      | -> panel                 |
      | -> picker                |
      | -> resizer               |
      | -> rtl                   |
      | -> scroll                |
      | -> selection             |
      | -> slider                |
      | -> sparkline             |
      | -> state                 |
      | -> tab                   |
      | -> tip                   |
      | -> toolbar               |
      | -> tree                  |
      | -> util                  |
      | -> view                  |
      | -> widget                |
      | -> window                |
      | --\ AbstractPlugin.js    |
      | --\ Action.js            |
      | --\ Component.js         |
      | --\ ComponentLoader.js   |
      | --\ Editor.js            |
      | --\ ElementLoader.js     |
      | --\ enums.js             |
      | --\ FocusManager.js      |
      | --\ Img.js               |
      | --\ LoadMask.js          |
      | --\ PluginManager.js     |
      | --\ ProgressBar.js       |
      | --\ ProgressBarWidget.js |
      | --\ Shadow.js            |
      | --\ ShadowPool.js        |
      | --\ ZIndexManager.js     |

  Scenario: Verify Tree all values
    Given I open extjs6 app and add "#tree-xml" path
    When I expand all nodes in Tree
    Then I verify if Tree has values:
      | v Ext JS                       |
      | -v app                         |
      | --v bindinspector              |
      | ---v noconflict                |
      | -----\ BaseModel.js            |
      | ----\ ComponentDetail.js       |
      | ----\ ComponentList.js         |
      | ----\ Container.js             |
      | ----\ Environment.js           |
      | ----\ Inspector.js             |
      | ----\ Util.js                  |
      | ----\ ViewModelDetail.js       |
      | --v domain                     |
      | ----\ Component.js             |
      | ----\ Controller.js            |
      | ----\ Direct.js                |
      | ----\ Global.js                |
      | ----\ Store.js                 |
      | ----\ View.js                  |
      | --v route                      |
      | ----\ Queue.js                 |
      | ----\ Route.js                 |
      | ----\ Router.js                |
      | ---\ Application.js            |
      | ---\ BaseController.js         |
      | ---\ Controller.js             |
      | ---\ EventBus.js               |
      | ---\ EventDomain.js            |
      | ---\ Util.js                   |
      | ---\ ViewController.js         |
      | -v button                      |
      | ---\ Button.js                 |
      | ---\ Cycle.js                  |
      | ---\ Manager.js                |
      | ---\ Split.js                  |
      | -v container                   |
      | --v plugin                     |
      | ----\ Viewport.js              |
      | ---\ ButtonGroup.js            |
      | ---\ Container.js              |
      | ---\ DockingContainer.js       |
      | ---\ Monitor.js                |
      | ---\ Viewport.js               |
      | -v dashboard                   |
      | ---\ Column.js                 |
      | ---\ Dashboard.js              |
      | ---\ DropZone.js               |
      | ---\ Panel.js                  |
      | ---\ Part.js                   |
      | -v dd                          |
      | ---\ DD.js                     |
      | ---\ DDProxy.js                |
      | ---\ DDTarget.js               |
      | ---\ DragDrop.js               |
      | ---\ DragDropManager.js        |
      | ---\ DragSource.js             |
      | ---\ DragTracker.js            |
      | ---\ DragZone.js               |
      | ---\ DropTarget.js             |
      | ---\ DropZone.js               |
      | ---\ Registry.js               |
      | ---\ ScrollManager.js          |
      | ---\ StatusProxy.js            |
      | -v dom                         |
      | ---\ Layer.js                  |
      | -v flash                       |
      | ---\ Component.js              |
      | -v form                        |
      | --v action                     |
      | ----\ Action.js                |
      | ----\ DirectLoad.js            |
      | ----\ DirectSubmit.js          |
      | ----\ Load.js                  |
      | ----\ StandardSubmit.js        |
      | ----\ Submit.js                |
      | --v field                      |
      | ----\ Base.js                  |
      | ----\ Checkbox.js              |
      | ----\ ComboBox.js              |
      | ----\ Date.js                  |
      | ----\ Display.js               |
      | ----\ Field.js                 |
      | ----\ File.js                  |
      | ----\ FileButton.js            |
      | ----\ Hidden.js                |
      | ----\ HtmlEditor.js            |
      | ----\ Number.js                |
      | ----\ Picker.js                |
      | ----\ Radio.js                 |
      | ----\ Spinner.js               |
      | ----\ Tag.js                   |
      | ----\ Text.js                  |
      | ----\ TextArea.js              |
      | ----\ Time.js                  |
      | ----\ Trigger.js               |
      | ----\ VTypes.js                |
      | --v trigger                    |
      | ----\ Component.js             |
      | ----\ Spinner.js               |
      | ----\ Trigger.js               |
      | ---\ Basic.js                  |
      | ---\ CheckboxGroup.js          |
      | ---\ CheckboxManager.js        |
      | ---\ FieldAncestor.js          |
      | ---\ FieldContainer.js         |
      | ---\ FieldSet.js               |
      | ---\ Label.js                  |
      | ---\ Labelable.js              |
      | ---\ Panel.js                  |
      | ---\ RadioGroup.js             |
      | ---\ RadioManager.js           |
      | -v fx                          |
      | --v target                     |
      | ----\ Component.js             |
      | ----\ CompositeElement.js      |
      | ----\ CompositeElementCSS.js   |
      | ----\ CompositeSprite.js       |
      | ----\ Element.js               |
      | ----\ ElementCSS.js            |
      | ----\ Sprite.js                |
      | ----\ Target.js                |
      | ---\ Anim.js                   |
      | ---\ Animator.js               |
      | ---\ CubicBezier.js            |
      | ---\ DrawPath.js               |
      | ---\ Easing.js                 |
      | ---\ Manager.js                |
      | ---\ PropertyHandler.js        |
      | ---\ Queue.js                  |
      | -v grid                        |
      | --v column                     |
      | ----\ Action.js                |
      | ----\ Boolean.js               |
      | ----\ Check.js                 |
      | ----\ Column.js                |
      | ----\ Date.js                  |
      | ----\ Number.js                |
      | ----\ RowNumberer.js           |
      | ----\ Template.js              |
      | ----\ Widget.js                |
      | --v feature                    |
      | ----\ AbstractSummary.js       |
      | ----\ Feature.js               |
      | ----\ Grouping.js              |
      | ----\ GroupingSummary.js       |
      | ----\ GroupStore.js            |
      | ----\ RowBody.js               |
      | ----\ Summary.js               |
      | --v header                     |
      | ----\ Container.js             |
      | ----\ DragZone.js              |
      | ----\ DropZone.js              |
      | --v locking                    |
      | ----\ HeaderContainer.js       |
      | ----\ Lockable.js              |
      | ----\ View.js                  |
      | --v plugin                     |
      | ----\ BufferedRenderer.js      |
      | ----\ CellEditing.js           |
      | ----\ DragDrop.js              |
      | ----\ Editing.js               |
      | ----\ HeaderReorderer.js       |
      | ----\ HeaderResizer.js         |
      | ----\ RowEditing.js            |
      | ----\ RowExpander.js           |
      | --v property                   |
      | ----\ Grid.js                  |
      | ----\ HeaderContainer.js       |
      | ----\ Property.js              |
      | ----\ Store.js                 |
      | ---\ CellContext.js            |
      | ---\ CellEditor.js             |
      | ---\ ColumnComponentLayout.js  |
      | ---\ ColumnLayout.js           |
      | ---\ ColumnManager.js          |
      | ---\ Panel.js                  |
      | ---\ RowEditor.js              |
      | ---\ RowEditorButtons.js       |
      | ---\ Scroller.js               |
      | ---\ View.js                   |
      | ---\ ViewDropZone.js           |
      | -v layout                      |
      | --v component                  |
      | ---v field                     |
      | -----\ FieldContainer.js       |
      | -----\ HtmlEditor.js           |
      | ----\ Auto.js                  |
      | ----\ Body.js                  |
      | ----\ BoundList.js             |
      | ----\ Button.js                |
      | ----\ Component.js             |
      | ----\ Dock.js                  |
      | ----\ FieldSet.js              |
      | ----\ ProgressBar.js           |
      | --v container                  |
      | ---v border                    |
      | -----\ Region.js               |
      | ---v boxOverflow               |
      | -----\ Menu.js                 |
      | -----\ None.js                 |
      | -----\ Scroller.js             |
      | ----\ Absolute.js              |
      | ----\ Accordion.js             |
      | ----\ Anchor.js                |
      | ----\ Auto.js                  |
      | ----\ Border.js                |
      | ----\ Box.js                   |
      | ----\ Card.js                  |
      | ----\ Center.js                |
      | ----\ CheckboxGroup.js         |
      | ----\ Column.js                |
      | ----\ ColumnSplitter.js        |
      | ----\ ColumnSplitterTracker.js |
      | ----\ Container.js             |
      | ----\ Editor.js                |
      | ----\ Fit.js                   |
      | ----\ Form.js                  |
      | ----\ HBox.js                  |
      | ----\ SplitColumn.js           |
      | ----\ Table.js                 |
      | ----\ VBox.js                  |
      | ---\ ClassList.js              |
      | ---\ Context.js                |
      | ---\ ContextItem.js            |
      | ---\ Layout.js                 |
      | ---\ SizeModel.js              |
      | ---\ SizePolicy.js             |
      | -v menu                        |
      | ---\ CheckItem.js              |
      | ---\ ColorPicker.js            |
      | ---\ DatePicker.js             |
      | ---\ Item.js                   |
      | ---\ KeyNav.js                 |
      | ---\ Manager.js                |
      | ---\ Menu.js                   |
      | ---\ Separator.js              |
      | -v panel                       |
      | ---\ DD.js                     |
      | ---\ Header.js                 |
      | ---\ Panel.js                  |
      | ---\ Pinnable.js               |
      | ---\ Proxy.js                  |
      | ---\ Table.js                  |
      | ---\ Tool.js                   |
      | -v picker                      |
      | ---\ Color.js                  |
      | ---\ Date.js                   |
      | ---\ Month.js                  |
      | ---\ Time.js                   |
      | -v resizer                     |
      | ---\ BorderSplitter.js         |
      | ---\ BorderSplitterTracker.js  |
      | ---\ Handle.js                 |
      | ---\ Resizer.js                |
      | ---\ ResizeTracker.js          |
      | ---\ Splitter.js               |
      | ---\ SplitterTracker.js        |
      | -v rtl                         |
      | --v button                     |
      | ----\ Button.js                |
      | --v dd                         |
      | ----\ DD.js                    |
      | --v dom                        |
      | ----\ Element.js               |
      | ----\ Layer.js                 |
      | --v event                      |
      | ----\ Event.js                 |
      | --v form                       |
      | ---v field                     |
      | -----\ Checkbox.js             |
      | -----\ File.js                 |
      | -----\ FileButton.js           |
      | -----\ Spinner.js              |
      | ----\ Labelable.js             |
      | --v grid                       |
      | ---v column                    |
      | -----\ Column.js               |
      | ---v feature                   |
      | -----\ Summary.js              |
      | ---v plugin                    |
      | -----\ HeaderResizer.js        |
      | -----\ RowEditing.js           |
      | ----\ CellEditor.js            |
      | ----\ ColumnLayout.js          |
      | ----\ RowEditor.js             |
      | --v layout                     |
      | ---v component                 |
      | -----\ Dock.js                 |
      | ---v container                 |
      | ----v boxOverflow              |
      | ------\ Menu.js                |
      | ------\ Scroller.js            |
      | -----\ Absolute.js             |
      | -----\ Border.js               |
      | -----\ Box.js                  |
      | -----\ Column.js               |
      | -----\ HBox.js                 |
      | -----\ VBox.js                 |
      | ----\ ContextItem.js           |
      | --v panel                      |
      | ----\ Header.js                |
      | ----\ Panel.js                 |
      | --v resizer                    |
      | ----\ BorderSplitterTracker.js |
      | ----\ ResizeTracker.js         |
      | ----\ SplitterTracker.js       |
      | --v scroll                     |
      | ----\ Manager.js               |
      | ----\ Scroller.js              |
      | --v selection                  |
      | ----\ CellModel.js             |
      | ----\ TreeModel.js             |
      | --v slider                     |
      | ----\ Multi.js                 |
      | --v tab                        |
      | ----\ Bar.js                   |
      | --v tip                        |
      | ----\ QuickTipManager.js       |
      | --v tree                       |
      | ----\ Column.js                |
      | --v util                       |
      | ----\ Floating.js              |
      | ----\ Renderable.js            |
      | --v view                       |
      | ----\ Table.js                 |
      | ---\ Component.js              |
      | -v scroll                      |
      | ---\ Indicator.js              |
      | ---\ Manager.js                |
      | -v selection                   |
      | ---\ CellModel.js              |
      | ---\ CheckboxModel.js          |
      | ---\ DataViewModel.js          |
      | ---\ Model.js                  |
      | ---\ RowModel.js               |
      | ---\ TreeModel.js              |
      | -v slider                      |
      | ---\ Multi.js                  |
      | ---\ Single.js                 |
      | ---\ Thumb.js                  |
      | ---\ Tip.js                    |
      | ---\ Widget.js                 |
      | -v sparkline                   |
      | ---\ Bar.js                    |
      | ---\ BarBase.js                |
      | ---\ Base.js                   |
      | ---\ Box.js                    |
      | ---\ Bullet.js                 |
      | ---\ CanvasBase.js             |
      | ---\ CanvasCanvas.js           |
      | ---\ Discrete.js               |
      | ---\ Line.js                   |
      | ---\ Pie.js                    |
      | ---\ RangeMap.js               |
      | ---\ Shape.js                  |
      | ---\ TriState.js               |
      | ---\ VmlCanvas.js              |
      | -v state                       |
      | ---\ CookieProvider.js         |
      | ---\ LocalStorageProvider.js   |
      | ---\ Manager.js                |
      | ---\ Provider.js               |
      | ---\ Stateful.js               |
      | -v tab                         |
      | ---\ Bar.js                    |
      | ---\ Panel.js                  |
      | ---\ Tab.js                    |
      | -v tip                         |
      | ---\ QuickTip.js               |
      | ---\ QuickTipManager.js        |
      | ---\ Tip.js                    |
      | ---\ ToolTip.js                |
      | -v toolbar                     |
      | ---\ Fill.js                   |
      | ---\ Item.js                   |
      | ---\ Paging.js                 |
      | ---\ Separator.js              |
      | ---\ Spacer.js                 |
      | ---\ TextItem.js               |
      | ---\ Toolbar.js                |
      | -v tree                        |
      | --v plugin                     |
      | ----\ TreeViewDragDrop.js      |
      | ---\ Column.js                 |
      | ---\ Panel.js                  |
      | ---\ View.js                   |
      | ---\ ViewDragZone.js           |
      | ---\ ViewDropZone.js           |
      | -v util                        |
      | ---\ Animate.js                |
      | ---\ Bindable.js               |
      | ---\ ClickRepeater.js          |
      | ---\ ComponentDragger.js       |
      | ---\ Cookies.js                |
      | ---\ CSS.js                    |
      | ---\ ElementContainer.js       |
      | ---\ Floating.js               |
      | ---\ History.js                |
      | ---\ KeyMap.js                 |
      | ---\ KeyNav.js                 |
      | ---\ Memento.js                |
      | ---\ Positionable_ext.js       |
      | ---\ ProtoElement.js           |
      | ---\ Queue.js                  |
      | ---\ Renderable.js             |
      | ---\ TextMetrics.js            |
      | -v view                        |
      | ---\ AbstractView.js           |
      | ---\ BoundList.js              |
      | ---\ BoundListKeyNav.js        |
      | ---\ DragZone.js               |
      | ---\ DropZone.js               |
      | ---\ MultiSelector.js          |
      | ---\ MultiSelectorSearch.js    |
      | ---\ NodeCache.js              |
      | ---\ Table.js                  |
      | ---\ TableLayout.js            |
      | ---\ View.js                   |
      | --\ widget                     |
      | -v window                      |
      | ---\ MessageBox.js             |
      | ---\ Toast.js                  |
      | ---\ Window.js                 |
      | --\ AbstractPlugin.js          |
      | --\ Action.js                  |
      | --\ Component.js               |
      | --\ ComponentLoader.js         |
      | --\ Editor.js                  |
      | --\ ElementLoader.js           |
      | --\ enums.js                   |
      | --\ FocusManager.js            |
      | --\ Img.js                     |
      | --\ LoadMask.js                |
      | --\ PluginManager.js           |
      | --\ ProgressBar.js             |
      | --\ ProgressBarWidget.js       |
      | --\ Shadow.js                  |
      | --\ ShadowPool.js              |
      | --\ ZIndexManager.js           |