Ext.onReady(function(){
    var fm = Ext.form;

    var store = new Ext.data.ArrayStore({
            fields: ['state'],
            data : [
                ['Arabic'],
                ['Bengali'],
                ['Bulgarian'],
                ['Chinese(Simplified)'],
                ['Chinese(Traditional)'],
                ['Czech'],
                ['Danish'],
                ['Dari'],
                ['Dutch'],
                ['Flemish'],
                ['English'],
                ['English(United States)'],
                ['English(United Kingdom)'],
                ['Estonian'],
                ['Finnish'],
                ['French'],
                ['French(Canada)'],
                ['French(France)'],
                ['German'],
                ['Greek'],
                ['Hausa'],
                ['Hebrew'],
                ['Hindi'],
                ['Hungarian'],
                ['Indonesian'],
                ['Italian'],
                ['Japanese'],
                ['Korean'],
                ['Latvian'],
                ['Lithuanian'],
                ['Maltese'],
                ['Norwegian'],
                ['Pushto'],
                ['Persian'],
                ['Polish'],
                ['Portuguese'],
                ['Portuguese(Brazil)'],
                ['Portuguese(Portugal)'],
                ['Romanian'],
                ['Russian'],
                ['Serbian'],
                ['Slovak'],
                ['Slovenian'],
                ['Somali'],
                ['Spanish'],
                ['Spanish(Mexico)'],
                ['Spanish(Spain)'],
                ['Swedish'],
                ['Thai'],
                ['Turkish'],
                ['Urdu'],
                ['Afar'],
                ['Abkhazian'],
                ['Achinese'],
                ['Acoli'],
                ['Adangme'],
                ['Adyghe'],
                ['Afro - Asiatic languages'],
                ['Afrihili'],
                ['Afrikaans'],
                ['Ainu'],
                ['Akan'],
                ['Akkadian'],
                ['Albanian'],
                ['Aleut'],
                ['Algonquian languages'],
                ['Southern Altai'],
                ['Amharic'],
                ['English, Old(ca .450 - 1100)'],
                ['Angika'],
                ['Apache languages'],
                ['Official Aramaic (700 - 300 BCE)'],
                ['Aragonese'],
                ['Armenian'],
                ['Mapudungun'],
                ['Arapaho'],
                ['Artificial languages'],
                ['Arawak'],
                ['Assamese'],
                ['Asturian'],
                ['Athapascan languages'],
                ['Australian languages'],
                ['Avaric'],
                ['Avestan'],
                ['Awadhi'],
                ['Aymara'],
                ['Azerbaijani'],
                ['Banda languages'],
                ['Bamileke languages'],
                ['Bashkir'],
                ['Baluchi'],
                ['Bambara'],
                ['Balinese'],
                ['Basque'],
                ['Basa'],
                ['Baltic languages'],
                ['Beja'],
                ['Belarusian'],
                ['Bemba'],
                ['Berber languages'],
                ['Bhojpuri'],
                ['Bihari'],
                ['Bikol'],
                ['Bini'],
                ['Bislama'],
                ['Siksika'],
                ['Bantu languages'],
                ['Bosnian'],
                ['Braj'],
                ['Breton'],
                ['Batak languages'],
                ['Buriat'],
                ['Buginese'],
                ['Burmese'],
                ['Blin'],
                ['Caddo'],
                ['Central American Indian languages'],
                ['Galibi Carib'],
                ['Catalan'],
                ['Caucasian languages'],
                ['Cebuano'],
                ['Celtic languages'],
                ['Chamorro'],
                ['Chibcha'],
                ['Chechen'],
                ['Chagatai'],
                ['Chuukese'],
                ['Mari'],
                ['Chinook Jargon'],
                ['Choctaw'],
                ['Chipewyan'],
                ['Cherokee'],
                ['Church Slavic'],
                ['Chuvash'],
                ['Cheyenne'],
                ['Chamic languages'],
                ['Coptic'],
                ['Cornish'],
                ['Corsican'],
                ['Creoles and pidgins, English based'],
                ['Creoles and pidgins, French - based'],
                ['Creoles and pidgins, Portuguese - based'],
                ['Cree'],
                ['Crimean Tatar'],
                ['Creoles and pidgins'],
                ['Kashubian'],
                ['Cushitic languages'],
                ['Dakota'],
                ['Dargwa'],
                ['Land Dayak languages'],
                ['Delaware'],
                ['Slave(Athapascan)'],
                ['Dogrib'],
                ['Dinka'],
                ['Divehi'],
                ['Dogri'],
                ['Dravidian languages'],
                ['Lower Sorbian'],
                ['Duala'],
                ['Dutch, Middle(ca .1050 - 1350)'],
                ['Dyula'],
                ['Dzongkha'],
                ['Efik'],
                ['Egyptian(Ancient)'],
                ['Ekajuk'],
                ['Elamite'],
                ['English'],
                ['English, Middle(1100 - 1500)'],
                ['Esperanto'],
                ['Ewe'],
                ['Ewondo'],
                ['Fang'],
                ['Faroese'],
                ['Fanti'],
                ['Fijian'],
                ['Filipino'],
                ['Finno - Ugrian languages'],
                ['Fon'],
                ['French, Middle(ca .1400 - 1600)'],
                ['French, Old(842 - ca .1400)'],
                ['Northern Frisian'],
                ['Eastern Frisian'],
                ['Western Frisian'],
                ['Fulah'],
                ['Friulian'],
                ['Ga'],
                ['Gayo'],
                ['Gbaya'],
                ['Germanic languages'],
                ['Georgian'],
                ['Geez'],
                ['Gilbertese'],
                ['Gaelic'],
                ['Irish'],
                ['Galician'],
                ['Manx'],
                ['German, Middle High(ca .1050 - 1500)'],
                ['German, Old High(ca .750 - 1050)'],
                ['Gondi'],
                ['Gorontalo'],
                ['Gothic'],
                ['Grebo'],
                ['Greek, Ancient(to 1453)'],
                ['Guarani'],
                ['Swiss German'],
                ['Gujarati'],
                ['Hawaiian'],
                ['Herero'],
                ['Hiligaynon'],
                ['Himachali'],
                ['Hittite'],
                ['Hmong'],
                ['Hiri Motu'],
                ['Croatian'],
                ['Upper Sorbian'],
                ['Hupa'],
                ['Iban'],
                ['Igbo'],
                ['Icelandic'],
                ['Ido'],
                ['Sichuan Yi'],
                ['Ijo languages'],
                ['Inuktitut'],
                ['Interlingue'],
                ['Iloko'],
                ['Interlingua(International Auxiliary Language Association)'],
                ['Indic languages'],
                ['Indo - European languages'],
                ['Ingush'],
                ['Inupiaq'],
                ['Iranian languages'],
                ['Iroquoian languages'],
                ['Javanese'],
                ['Lojban'],
                ['Judeo - Persian'],
                ['Judeo - Arabic'],
                ['Kara - Kalpak'],
                ['Kabyle'],
                ['Kachin'],
                ['Kalaallisut'],
                ['Kamba'],
                ['Kannada'],
                ['Karen languages'],
                ['Kashmiri'],
                ['Kanuri'],
                ['Kawi'],
                ['Kazakh'],
                ['Kabardian'],
                ['Khasi'],
                ['Khoisan languages'],
                ['Central Khmer'],
                ['Khotanese'],
                ['Kikuyu'],
                ['Kinyarwanda'],
                ['Kirghiz'],
                ['Kimbundu'],
                ['Konkani'],
                ['Komi'],
                ['Kongo'],
                ['Kosraean'],
                ['Kpelle'],
                ['Karachay - Balkar'],
                ['Karelian'],
                ['Kru languages'],
                ['Kurukh'],
                ['Kuanyama'],
                ['Kumyk'],
                ['Kurdish'],
                ['Kutenai'],
                ['Ladino'],
                ['Lahnda'],
                ['Lamba'],
                ['Lao'],
                ['Latin'],
                ['Lezghian'],
                ['Limburgan'],
                ['Lingala'],
                ['Mongo'],
                ['Lozi'],
                ['Luxembourgish'],
                ['Luba - Lulua'],
                ['Luba - Katanga'],
                ['Ganda'],
                ['Luiseno'],
                ['Lunda'],
                ['Luo(Kenya and Tanzania)'],
                ['Lushai'],
                ['Macedonian'],
                ['Madurese'],
                ['Magahi'],
                ['Marshallese'],
                ['Maithili'],
                ['Makasar'],
                ['Malayalam'],
                ['Mandingo'],
                ['Maori'],
                ['Austronesian languages'],
                ['Marathi'],
                ['Masai'],
                ['Malay'],
                ['Moksha'],
                ['Mandar'],
                ['Mende'],
                ['Irish, Middle(900 - 1200)'],
                ['Minangkabau'],
                ['Uncoded languages'],
                ['Mon - Khmer languages'],
                ['Malagasy'],
                ['Manchu'],
                ['Manipuri'],
                ['Manobo languages'],
                ['Mohawk'],
                ['Mongolian'],
                ['Mossi'],
                ['Multiple languages'],
                ['Munda languages'],
                ['Creek'],
                ['Mirandese'],
                ['Marwari'],
                ['Mayan languages'],
                ['Erzya'],
                ['Nahuatl languages'],
                ['North American Indian languages'],
                ['Neapolitan'],
                ['Nauru'],
                ['Navajo'],
                ['Ndebele'],
                ['Ndebele'],
                ['Ndonga'],
                ['Low German'],
                ['Nepali'],
                ['Nias'],
                ['Niger - Kordofanian languages'],
                ['Niuean'],
                ['Nyamwezi'],
                ['Nyankole'],
                ['Nyoro'],
                ['Nzima'],
                ['Occitan(post 1500)'],
                ['Ojibwa'],
                ['Oriya'],
                ['Oromo'],
                ['Osage'],
                ['Turkish, Ottoman(1500 - 1928)'],
                ['Otomian languages'],
                ['Papuan languages'],
                ['Pangasinan'],
                ['Pahlavi'],
                ['Papiamento'],
                ['Palauan'],
                ['Persian, Old(ca .600 - 400 B.C.)'],
                ['Philippine languages'],
                ['Phoenician'],
                ['Pali'],
                ['Pohnpeian'],
                ['Prakrit languages'],
                ['Proven‡al, Old(to 1500); Occitan, Old(to 1500)'],
                ['Quechua'],
                ['Rajasthani'],
                ['Rapanui'],
                ['Romance languages'],
                ['Romansh'],
                ['Romany'],
                ['Rundi'],
                ['Sandawe'],
                ['Sango'],
                ['Yakut'],
                ['South American Indian languages'],
                ['Salishan languages'],
                ['Samaritan Aramaic'],
                ['Sanskrit'],
                ['Sasak'],
                ['Santali'],
                ['Sicilian'],
                ['Scots'],
                ['Selkup'],
                ['Semitic languages'],
                ['Irish, Old(to 900)'],
                ['Sign Languages'],
                ['Shan'],
                ['Sidamo'],
                ['Siouan languages'],
                ['Sino - Tibetan languages'],
                ['Slavic languages'],
                ['Southern Sami'],
                ['Northern Sami'],
                ['Sami languages'],
                ['Lule Sami'],
                ['Inari Sami'],
                ['Samoan'],
                ['Skolt Sami'],
                ['Shona'],
                ['Sindhi'],
                ['Soninke'],
                ['Sogdian'],
                ['Songhai languages'],
                ['Sotho, Southern'],
                ['Sardinian'],
                ['Sranan Tongo'],
                ['Serer'],
                ['Nilo - Saharan languages'],
                ['Swati'],
                ['Sukuma'],
                ['Sundanese'],
                ['Susu'],
                ['Sumerian'],
                ['Swahili'],
                ['Classical Syriac'],
                ['Syriac'],
                ['Tahitian'],
                ['Tai languages'],
                ['Tamil'],
                ['Tatar'],
                ['Telugu'],
                ['Timne'],
                ['Tereno'],
                ['Tetum'],
                ['Tajik'],
                ['Tagalog'],
                ['Tibetan'],
                ['Tigre'],
                ['Tigrinya'],
                ['Tiv'],
                ['Tokelau'],
                ['Tlingit'],
                ['Tamashek'],
                ['Tonga(Nyasa)'],
                ['Tonga(Tonga Islands)'],
                ['Tok Pisin'],
                ['Tsimshian'],
                ['Tswana'],
                ['Tsonga'],
                ['Turkmen'],
                ['Tumbuka'],
                ['Tupi languages'],
                ['Altaic languages'],
                ['Tuvalu'],
                ['Twi'],
                ['Tuvinian'],
                ['Udmurt'],
                ['Ugaritic'],
                ['Ukrainian'],
                ['Umbundu'],
                ['Undetermined'],
                ['Uzbek'],
                ['Vai'],
                ['Venda'],
                ['Vietnamese'],
                ['Volap ? k'],
                ['Votic'],
                ['Wakashan languages'],
                ['Waray'],
                ['Washo'],
                ['Welsh'],
                ['Sorbian languages'],
                ['Walloon'],
                ['Wolof'],
                ['Xhosa'],
                ['Yao'],
                ['Yapese'],
                ['Yiddish'],
                ['Yoruba'],
                ['Yupik languages'],
                ['Zapotec'],
                ['Zenaga'],
                ['Zande languages'],
                ['Zulu'],
                ['Zuni']
            ]
        });

    var combo = new Ext.form.ComboBox({
                store: store,
                displayField: 'state',
                name: 'comboBox',
                typeAhead: true,
                mode: 'local',
                triggerAction: 'all',
                emptyText:'Select a state...',
                selectOnFocus:true,
                width:135
            });

    var showComponentButton = new Ext.Button({
        text: 'ComboBox',
        handler: function(){
            var win = new Ext.Window({
                title: 'ComboBoxWindow',
                layout:'fit',
                width:400,
                height:400,
                plain: true,

                items: combo,

                buttons: [{
                    text:'Submit',
                    disabled:true
                },{
                    text: 'Close',
                    handler: function(){
                        win.close();
                    }
                }]
            });
            win.show();
        }
    });

    Testy.topToolbar.add(showComponentButton);
    Testy.topToolbar.doLayout();
});
